on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Pull latest code on Windows VM
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -v VMadmin@${{ secrets.SSH_HOST }} "echo SSH Connected"
      - name: Connect to Windows VM and pull latest code
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /f/myproject/training-backend && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
      

      - name: Cleanup
        run: rm -rf ~/.ssh
